### ISSUE TITLE
python3 syntax error

### ISSUE THREAD

**Issue by lethliel** [openSUSE/osc-plugin-collab#50]
here seems to be a problem with the new  osc-plugin-collab-0.99-bp151.2.6.noarch

lkocman@linux-zrtn:~/Workspace/ibs/home:lkocman:branches:SUSE:SLE-15-SP1:GA/000package-groups> iosc log
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9203, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/osc-plugins/osc-collab.py", line 550
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax

/usr/lib/osc-plugins/osc-collab.py: invalid syntax (osc-collab.py, line 550)

**Comment by lethliel** [comment]
originally reported by @lkocman

**Comment by JeffreyCheung** [comment]
Hi I encountered this error today, do we have any fix now ?

**Comment by JeffreyCheung** [comment]
OK, I remove osc-plugin-collab to bypass this error.

**Comment by vuntz** [comment]
This was fixed in 4e37cccedd0840681f6d5a4f917edd78d9a99752 back in May...

**Comment by Twoflower2** [comment]
Still fails in Leap 15.2

```
$  osc -A https://api.suse.de api 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9356, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/osc-plugins/osc-collab.py", line 550
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax

/usr/lib/osc-plugins/osc-collab.py: invalid syntax (osc-collab.py, line 550)

 Try 'env OSC_PLUGIN_FAIL_IGNORE=1 osc ...'
```

```
Version: 0.99-lp152.3.2
Provides: osc-plugin-collab = 0.99-lp152.3.2
Requires: rpmlib(CompressedFileNames) <= 3.0.4-1rpmlib(FileDigests) <= 4.6.0-1rpmlib(PayloadFilesHavePrefix) <= 4.0-1rpmlib(PayloadIsXz) <= 5.2-1osc >= 0.140.1
Conflicts: osc-plugins-gnome <= 0.4.26
Recommends: xzquiltrpm-python

**Comment by vuntz** [comment]
> Still fails in Leap 15.2

For the record, this got moved to https://github.com/openSUSE/osc-plugin-collab/issues/56
